# Generated by Django 5.2.17 on 2026-09-14 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('elementary', 'Elementary School'), ('junior', 'Junior High School'), ('senior', 'Senior High School'), ('bachelor', "Bachelor's Degree")], default='bachelor', max_length=20)),
                ('logo', models.URLField(blank=True, null=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
