# Generated by Django 5.2.17 on 2026-09-20 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('film', 'Film & Video'), ('software', 'Software / Web'), ('design', 'Design'), ('writing', 'Writing'), ('music', 'Music / Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('project_url', models.URLField()),
                ('completed_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
