# Generated by Django 5.2.17 on 2026-09-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed_at',
        ),
    ]
