# Generated by Django 5.2.17 on 2026-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major_indo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Major (Indonesian)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_indo',
            field=models.TextField(blank=True, default='', verbose_name='Description (Indonesian)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_indo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Role (Indonesian)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_indo',
            field=models.TextField(blank=True, default='', verbose_name='Description (Indonesian)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_indo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title (Indonesian)'),
        ),
    ]
