# Generated by Django 5.2.17 on 2026-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_education_major_indo_experience_description_indo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='photos',
            field=models.TextField(blank=True, default='', verbose_name='More photos (one URL per line)'),
        ),
    ]
